#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: generic

dist: xenial

#-----------------------------------------------------------------------------

addons:
  homebrew:
    packages:
      - cmake
      - spatialite-tools
    update: true

#-----------------------------------------------------------------------------

matrix:
  include:

    # Linux Clang Builds
    - os: linux
      compiler: linux-clang38-dev
      addons:
        apt:
          packages: ['clang-3.8', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='clang++-3.8' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-clang39-dev
      addons:
        apt:
          packages: ['clang-3.9', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='clang++-3.9' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-clang40-dev
      addons:
        apt:
          packages: ['clang-4.0', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='clang++-4.0' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-clang50-dev
      addons:
        apt:
          packages: ['clang-5.0', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='clang++-5.0' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-clang60-dev
      addons:
        apt:
          packages: ['clang-6.0', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='clang++-6.0' BUILD_TYPE='Dev'

    - os: linux
      dist: bionic
      compiler: linux-clang7-dev
      addons:
        apt:
          packages: ['clang-7', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='clang++-7' BUILD_TYPE='Dev'

    - os: linux
      dist: bionic
      compiler: linux-clang7-release
      addons:
        apt:
          packages: ['pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin', 'clang-7', 'clang-tidy-7']
      env: CXX='clang++-7' BUILD_TYPE='Release' CLANG_TIDY=clang-tidy-7

    # Linux GCC Builds
    - os: linux
      compiler: linux-gcc48-dev
      addons:
        apt:
          packages: ['g++-4.8', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='g++-4.8' BUILD_TYPE='Dev' CXXFLAGS='-Wno-return-type'

    - os: linux
      compiler: linux-gcc49-dev
      addons:
        apt:
          packages: ['g++-4.9', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='g++-4.9' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-gcc5-dev
      addons:
        apt:
          packages: ['g++-5', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='g++-5' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-gcc6-dev
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: ['g++-6', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='g++-6' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-gcc7-dev
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: ['g++-7', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='g++-7' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-gcc7-release
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: ['g++-7', 'pandoc', 'libgdal1-dev', 'libgeos-dev', 'sqlite3', 'spatialite-bin']
      env: CXX='g++-7' BUILD_TYPE='Release'


    # OSX Clang Builds
    - os: osx
      osx_image: xcode9.4
      compiler: xcode9-clang-dev
      env: CXX='clang++' BUILD_TYPE='Dev'

    - os: osx
      osx_image: xcode10.2
      compiler: xcode10-clang-dev
      env: CXX='clang++' BUILD_TYPE='Dev'

    - os: osx
      osx_image: xcode11
      compiler: xcode11-clang-dev
      env: CXX='clang++' BUILD_TYPE='Dev'

    - os: osx
      osx_image: xcode11
      compiler: xcode11-clang-release
      env: CXX='clang++' BUILD_TYPE='Release'

#-----------------------------------------------------------------------------

install:
  - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
  - git clone --quiet --depth 1 https://github.com/mapbox/protozero.git ../protozero
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake -LA .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCLANG_TIDY=$(which ${CLANG_TIDY})

script:
  - make VERBOSE=1 && ctest --output-on-failure
  - if [ -n "${CLANG_TIDY}" ]; then make clang-tidy; fi

#-----------------------------------------------------------------------------
